### ISSUE TITLE
Inconsistent feature name

### ISSUE THREAD

**Issue by MarcoCicognani** [mvdnes/spin-rs#101]
Hi, very good crate, it as undergone a strong improvement from the version 0.5 that is use.

As i said in the title i noticed that the `lock_api` feature is named `lock_api1` into the code, making impossible for the users to enable that feature.

Keep it up!

**Comment by zesterer** [comment]
This is such that the feature does not conflict with the crate name, but I can realias the crate name. I'll put that on my list of things to do!

**Comment by zesterer** [comment]
This is fixed by https://github.com/mvdnes/spin-rs/pull/102 and has been released as part of version `0.8`.
