### ISSUE TITLE
`lock_api` feature is not available in version 0.7.1 and 0.8.0.

### ISSUE THREAD

**Issue by rise0chen** [mvdnes/spin-rs#103]

**Comment by zesterer** [comment]
What do you mean by 'not available'?

**Comment by rise0chen** [comment]
can't compile

**Comment by zesterer** [comment]
The `lock_api1` feature was removed in favour of `lock_api` in `0.8.0`. Are you sure you're using the correct feature name?

**Comment by zesterer** [comment]
I've published `0.9.0` which fixes this issue among others.
