### ISSUE TITLE
Cannot borrow `lazy::Lazy<T>` mutably?

### ISSUE THREAD

**Issue by ethindp** [mvdnes/spin-rs#107]
I have the following type:
```rust
type IrqList = FnvIndexMap<u8, MiniVec<InterruptHandler>, 256>;
pub type InterruptHandler = Box<dyn Fn(InterruptStackFrameValue) + Send + Sync>;
```
However, doing this:
```rust
static IRQ_FUNCS: Lazy<IrqList> = Lazy::new(|| {
let mut table = IrqList::new();
(0 .. u8::MAX).for_each(|i| {
let v = MiniVec::<InterruptHandler>::new();
if table.insert(i, v).is_err() {
panic!("Cannot add ISR function table for interrupt {}!", i);
}
});
table
});
```
And then trying to modify that mutably gives me the error:
```
error[E0596]: cannot borrow data in a dereference of `spin::lazy::Lazy<IndexMap<u8, MiniVec<alloc::boxed::Box<dyn Fn(InterruptStackFrameValue) + Send + Sync>>, hash32::BuildHasherDefault<hash32::fnv::Hasher>, 256_usize>, fn() -> IndexMap<u8, MiniVec<alloc::boxed::Box<dyn Fn(InterruptStackFrameValue) + Send + Sync>>, hash32::BuildHasherDefault<hash32::fnv::Hasher>, 256_usize>>` as mutable
   --> src/interrupts.rs:796:26
    |
796 |     if let Some(funcs) = IRQ_FUNCS.get_mut(&interrupt) {
    |                          ^^^^^^^^^ cannot borrow as mutable
    |
    = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `spin::lazy::Lazy<IndexMap<u8, MiniVec<alloc::boxed::Box<dyn Fn(InterruptStackFrameValue) + Send + Sync>>, hash32::BuildHasherDefault<hash32::fnv::Hasher>, 256_usize>, fn() -> IndexMap<u8, MiniVec<alloc::boxed::Box<dyn Fn(InterruptStackFrameValue) + Send + Sync>>, hash32::BuildHasherDefault<hash32::fnv::Hasher>, 256_usize>>`
```
Is this a problem with spin::lazy::Lazy itself? Or is this a problem with whatever is within it? This used to work with `lazy_static` but doesn't work like this for some reason. And DerefMut is not implemented for spin::lazy::Lazy. Is a lock more appropriate here?

**Comment by zesterer** [comment]
> Is this a problem with spin::lazy::Lazy itself? Or is this a problem with whatever is within it?

The latter. `Lazy` (and, indeed, `lazy_static`) do no guarantee mutual exclusivity, which is required to safely get a mutable reference to something. The only thing that they guarantee is synchronised, delayed initialisation of a value (hence the 'lazy' name).

If you want to have the resulting value *also* be accessible mutable, you need to guarantee mutual exclusion via some other type that performs synchronisation. Most likely, `Mutex` or `RwLock`. I can see that you're dealing with interrupts, so the implementations in `spin` will do (on targets with `std` support, use the ones in `std::sync`, of course). This would make the final type `Lazy<Mutex<IrqList>>`.

> This used to work with lazy_static but doesn't work like this for some reason.

I'm not sure how this would have worked without something like `Mutex`, `lazy_static` also does not guarantee exclusive access to the final value.

As a final note, I see that you're playing with interrupts: be very careful when combining interrupt code with synchronisation, and make sure that you never attempt to take locks (including spinlocks) in an interrupt handler. IRQs are not aware of any synchronisation primitives you have set up, and may well decide to fire when you're already in the critical section of a lock. If the interrupt handler then attempts to take that same lock, a deadlock will result.

**Comment by ethindp** [comment]
@zesterer Thank you. In IRQ handlers I gain immutable access to the type. Interrupts are disabled automatically by the processor before entering the handler -- I need to signal it with an EOI before it will give me the next one. This is specifically an x86-only project at the moment. Still, I will take what you said into consideration. (I could always just use an atomic to hold the items; then no locks would be needed at all. But that might not be a good idea either.

**Comment by zesterer** [comment]
Atomics are probably a good idea, yes!

**Comment by ethindp** [comment]
Is there a crate that will actually use atomics for everything? I'm hesitant to go implementing that myself.

**Comment by zesterer** [comment]
It's not possible in the general case. Atomic intrinsics usually only work for values up to 64 bits in size on most architectures. `atomic` has the following function that allows you to ensure that your operation is actually lock-free though: https://amanieu.github.io/atomic-rs/atomic/struct.Atomic.html#method.is_lock_free
