### ISSUE TITLE
Remove `panicked` field from Once's Finish guard

### ISSUE THREAD

**Issue by zesterer** [mvdnes/spin-rs#110]
The question is (albeit probably _very_ unlikely to make a difference), do we even need to perform that store? Because if `panic = 'unwind'` then IIRC panics will only execute destructors and not code, so shouldn't we be able to simply do `core::mem::forget(finish)`?

_Originally posted by @4lDO2 in https://github.com/mvdnes/spin-rs/pull/109#discussion_r665656678_

**Comment by 4lDO2** [comment]
I think this can be closed now, as this has been implemented by the recently merged PR above.

**Comment by zesterer** [comment]
Closed by #112
