### ISSUE TITLE
Implement Once::get_mut_unchecked and Once::into_inner_unchecked

### ISSUE THREAD

**Issue by zesterer** [mvdnes/spin-rs#111]
Oh, of course. If `get_unchecked_mut` takes `&mut self`, then it would certainly make sense to implement that. But again, probably in another PR.

_Originally posted by @4lDO2 in https://github.com/mvdnes/spin-rs/pull/109#discussion_r665730546_

**Comment by georglauterbach** [comment]
I'd really love to see this being implemented. Anything new?

**Comment by zesterer** [comment]
This could be fairly trivially implement if someone wants to do it. Otherwise, I might be able to pick this up in a few weeks.

**Comment by georglauterbach** [comment]
> This could be fairly trivially implement if someone wants to do it. Otherwise, I might be able to pick this up in a few weeks.

I will have a look and let you know whether there are any difficulties :D

**Comment by georglauterbach** [comment]
🚀
