### ISSUE TITLE
unwrap function in MutexGuard?

### ISSUE THREAD

**Issue by SergeyVolkovich99** [mvdnes/spin-rs#113]
Hello, recently i become writing nostd application but i getting error while trying to unwrap .lock() how it might be fixed?

**Comment by zesterer** [comment]
`spin`'s `Mutex` does not have lock poisoning, so you don't need use `.unwrao()`: the call to `.lock()` can never fail.

**Comment by SergeyVolkovich99** [comment]
simply problem in types, my function receive Arc<ThreadAtribute> but after .lock() i get MutexGuard<Arc<ThreadAttribute>>

**Comment by zesterer** [comment]
Is this resolved then?

**Comment by SergeyVolkovich99** [comment]
yes
