### ISSUE TITLE
portable_atomic feature does not compile

### ISSUE THREAD

**Issue by SUPERCILEX** [mvdnes/spin-rs#138]
```
error[E0599]: no method named `compare_exchange_weak` found for struct `AtomicBool` in the current scope
   --> /home/asaveau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spin-0.9.5/src/mutex/spin.rs:179:14
    |
179 |             .compare_exchange_weak(false, true, Ordering::Acquire, Ordering::Relaxed)
    |              ^^^^^^^^^^^^^^^^^^^^^ method not found in `AtomicBool`

error[E0599]: no method named `compare_exchange` found for struct `AtomicBool` in the current scope
   --> /home/asaveau/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spin-0.9.5/src/mutex/spin.rs:239:14
    |
239 |             .compare_exchange(false, true, Ordering::Acquire, Ordering::Relaxed)
    |              ^^^^^^^^^^^^^^^^ method not found in `AtomicBool`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `spin` due to 2 previous errors
```

On `riscv32i-unknown-none-elf`

**Comment by taiki-e** [comment]
riscv32i-unknown-none-elf does not have atomic CAS, so you need to enable cfg as described in the documentation or (after the #139 is released) enable the `critical-section ` feature of the `portable-atomic`.

https://github.com/mvdnes/spin-rs#feature-flags

> **The `portable_atomic_unsafe_assume_single_core` cfg flag must also be set by the final binary crate.**
> This can be done by adapting the following snippet to the `.cargo/config` file:
> ```
> [target.<target>]
> rustflags = [ "--cfg", "portable_atomic_unsafe_assume_single_core" ]
> ```
> Note that this cfg is unsafe by nature, and enabling it for multicore systems is unsound.

**Comment by SUPERCILEX** [comment]
Missed that, thanks!
