### ISSUE TITLE
Why was spin 0.9.6 yanked?

### ISSUE THREAD

**Issue by cbeck88** [mvdnes/spin-rs#146]
Hi, I've discovered that `spin 0.9.6` is yanked, which causes our CI to complain thanks to our use of `cargo deny`, but I can't find any information about why it was yanked.

There don't seem to be any release notes or even a commit in https://github.com/mvdnes/spin-rs/commits/master that documents the bump to 0.9.7.

Why should it be a priority for me to stop using 0.9.6?

**Comment by zesterer** [comment]
Whoops, forgot to push the version bump. TL;DR: there was a breaking change from 0.9 that was fixed.

**Comment by cbeck88** [comment]
Thanks
