### ISSUE TITLE
`Lazy` panics under bare metal environment

### ISSUE THREAD

**Issue by Lorilandly** [mvdnes/spin-rs#154]
Hi,
I was trying to replace `lazy_static!` with `Lazy`. While it works fine under normal environment (tried with rust playground), when I tried running it in bare metal (qemu rv64gc no compression), code panics with message: "Lazy instance has previously been poisoned" spin-0.9.8/src/lazy.rs: 100:21.
Here is the code segment
```
use spin::{Lazy, Mutex};

static ST: Lazy<Mutex<St>> = Lazy::new(||{
    let s = St::new();
    s.init();
    Mutex::new(s)
});
struct St {}

impl St {
    fn new() -> Self {
        println!("new");
        Self{}
    }
    
    fn init(&self) {
        println!("init");
    }
    
    fn dos(&mut self) {
        println!("did something mutable");
    }
}

pub extern "C" fn main() -> ! {
    // do initialization stuff

    ST.lock().dos();
    
    loop{
        unsafe { wfi() };
    }
}
```
In my understanding, `Lazy` should have the same behavior with `lazy_static`, or are they actually different and shouldn't be mix used? I'm using it primarily for initializing peripherals like uart and stuff, if there are better alternatives, please tell me. 
Thank you!

**Comment by zesterer** [comment]
This seems to me like a bug. I'm going to investigate this today.

**Comment by zesterer** [comment]
I've gone of the implementation quite carefully. Is there anything unusual about the platform you're running on? Perhaps unusual or non-existent support for atomics, or a CPU that starts with SMP enabled by default?

**Comment by Lorilandly** [comment]
Here is my qemu command 
```
qemu-system-riscv64 -M virt -smp 1 -m 128M \
            -display none -serial stdio \
            -bios none -kernel [PATH_TO_ELF]
```
The elf is compiled with the target `riscv64gc-unknown-none-elf` with the following rustflag
```
-Ctarget-feature=-c
```
I don't think there is there's anything unusual with the configuration. They are written to `.cargo/config.toml` file. I tried on macos and ubuntu, but the error is the same.

**Comment by zesterer** [comment]
Is it possible that you have something like an interrupt handler being invoked at an unexpected time?

**Comment by Lorilandly** [comment]
Just for debugging, I've changed the interrupt handler to
```
  .align 2
trap_entry:
  j 3f

3: // loop infinitely
  wfi
  j 3b
```
If the interrupt is invoked, it should end up in the dead-loop. Yet interrupt is not triggered, the code panics still.

**Comment by Lorilandly** [comment]
Thank you so much for this detailed explanation. The code was compiled with `#![no_std]` so it couldn't be the standard lib. After some troubleshooting I can confirm that the issue is caused by a bad alignment. However, it wasn't `sp`, but the alignment of `.data` section for whatever reason. I had:
```
.data : {
    . = ALIGN(4096);
    PROVIDE(_data_start = .);
    *(.sdata .sdata.*) *(.data .data.*)
    PROVIDE(_data_end = .);
} >RAM AT>RAM :data
```
When I changed it to
```
 .data : ALIGN(4096) {
    PROVIDE(_data_start = .);
    *(.sdata .sdata.*) *(.data .data.*)
    PROVIDE(_data_end = .);
} >RAM AT>RAM :data
```
the problem was solved. Some quirk with the linker!

Again, thank you so much for dealing with this bug that was caused by myself after all!

**Comment by taiki-e** [comment]
> The code was compiled with `#![no_std]` so it couldn't be the standard lib.

To be clear: I think "standard library" in my comment was misleading (I also meant core and alloc), but even with `no_std`, `core` is always linked, and it is also common to link to `alloc`. In riscv64gc-unknown-none-elf, both are precompiled libraries by default.

**Comment by Lorilandly** [comment]
Oh ok great! That actually answers why I was having some strange issues with core libs when I tries to run the binary on the real chip. Again thanks for the clarification😄
