### ISSUE TITLE
Use `std::hint::spin_loop` where it makes sense

### ISSUE THREAD

**Issue by Robbepop** [mvdnes/spin-rs#165]
Link: https://doc.rust-lang.org/std/hint/fn.spin_loop.html

I have the feeling that this Rust standard library component would be a great fit for the spin-loops in this library to further improve its efficiency on the architectures supported by it.
As mandated by its documentation `std::hint::spin_loop` is a no-op for unsupported architectures and does not interact with the operating system.

Please correct me if I am wrong about this.
I can file a PR if deemed useful/helpful.

**Comment by taiki-e** [comment]
I think it is already used. (std::hint::spin_loop and core::sync::atomic::spin_loop_hint is the same)

https://github.com/mvdnes/spin-rs/blob/e57cfd0ee0ac20cc0f0a25fb19c8f4db8cff01a3/src/relax.rs#L26-L29

**Comment by Robbepop** [comment]
> I think it is already used. (std::hint::spin_loop and core::sync::atomic::spin_loop_hint is the same)
> 
> https://github.com/mvdnes/spin-rs/blob/e57cfd0ee0ac20cc0f0a25fb19c8f4db8cff01a3/src/relax.rs#L26-L29

Ah okay, great, I didn't see it in the code. Thanks for the pointers. Closed then.
