### ISSUE TITLE
Once is not panic-robust

### ISSUE THREAD

**Issue by whitequark** [mvdnes/spin-rs#32]
Right now if the builder panics, all concurrent and future Once::call_once calls will be stuck forever.

**Comment by mvdnes** [comment]
Thanks for the bug report :+1:
I think this should solve it.

**Comment by whitequark** [comment]
There's one design point worth discussing here. Since the Once is not mutated before the builder properly returns, effectively no harm is done to it. So in principle you could reset it back to UNINITIALIZED. 

The current behavior is good if most panics inside the builder function are persistent. The behavior I describe is good if most panics inside the builder function are transient. I don't see an obvious benefit to either. What does the standard library do?

**Comment by whitequark** [comment]
Ah, the stdlib does what you do:

> The closure f will only be executed once if this is called concurrently amongst many threads. If that closure panics, however, then it will poison this Once instance, causing all future invocations of call_once to also panic.

That's fine with me then, thanks!

**Comment by mvdnes** [comment]
Yes that was what I was imitating.
