### ISSUE TITLE
cpu_relax for other architectures

### ISSUE THREAD

**Issue by cmr** [mvdnes/spin-rs#35]
Someone should investigate what, if anything, is worthwhile using in cpu_relax on non-x86 architectures.

**Comment by Dentosal** [comment]
I don't know lot about other architectures, but it looks like Linux uses `cpu_relax` with ARM. Unlike me, they might know what they are doing.

Macros form [https://android.googlesource.com/.../arm/include/asm/spinlock.h#67](https://android.googlesource.com/kernel/msm.git/+/7915d17d30f260b72fa90550014540ba4d156dfa/arch/arm/include/asm/spinlock.h#66) look like this:


    #define arch_spin_is_locked(x)		((x)->lock != 0)
    #define arch_spin_unlock_wait(lock) \
        do { while (arch_spin_is_locked(lock)) cpu_relax(); } while (0)

**Comment by Evrey** [comment]
This [code snippet](https://github.com/Tencent/mars/blob/master/mars/comm/thread/spinlock.h#L80-L99) here and this [ARM developer page](https://developer.arm.com/docs/100069/0607/a64-general-instructions/yield) suggest that `asm!("yield" :::: "volatile");` would be the way to go on AArch64, i.e. 64-bit ARMv8. [This read](http://cr.openjdk.java.net/~dchuyko/8186670/yield/spinwait.html) here might be of interest as well.

> # 6. Conclusions
>
> - We propose to add onSpinWait() intrinsic and SpinPause implementation in (Linux) AArch64 port with `yield` instruction.
> - It is harmless for CPUs that implement the instruction as NOP.
> - It should be benefitial for CPUs that have SMT or are able to partially shut down or pause for a while.
> - It may be considered to emit several nop instead of yield where latter works as nop to decrease memory pressure without loosing throughput.
>     - A concrete latency estimate for a potential implementation that should not cause any performance degradation for Java is around 16 cycles.

**Comment by tmccombs** [comment]
Rust added `core::sync::atomic::spin_loop_hint` somewhat recently. It would probably make sense to use that.

**Comment by brandenburg** [comment]
It appears @tmccombs's suggestion  has been adopted in 481c91392c51c5f7d0697030f4b7a4567e97c791 (thanks!). This issue can be closed.
