### ISSUE TITLE
default = ["unstable"]

### ISSUE THREAD

**Issue by ignatenkobrain** [mvdnes/spin-rs#37]
Does it really make sense?

**Comment by mvdnes** [comment]
I think so, since it is mostly targeted at people building an OS, which requires unstable features anyway.

**Comment by ignatenkobrain** [comment]
@mvdnes I wonder if you could rename "unstable" to "nightly" and remove it from default?

This would make much more sense because nightly feature is implicitly enabled on nightly compiler and it would just work on stable.

**Comment by mvdnes** [comment]
Is that true? I cannot find any reference to it being enabled automatically. Can you provide one? I am willing to rename it then.
