### ISSUE TITLE
Offer more efficient `cpu_relax` on certain platforms

### ISSUE THREAD

**Issue by clarcharr** [mvdnes/spin-rs#39]
For example, on Linux, we could use the `SCHED_YIELD` system call (code 24) that would yield to the OS scheduler instead of using `pause` for all x86 implementations. This also has the benefit of supporting more platforms efficiently.

**Comment by le-jzr** [comment]
What's the point of using a spin-lock if you can just call into scheduler? Seems to me like you'd just use synchronization from `std` in such cases.

**Comment by mvdnes** [comment]
I have to agree with @le-jzr. The `std` primitives use better suited systemcalls.
