### ISSUE TITLE
Documentation typo for call_once

### ISSUE THREAD

**Issue by kevinaboos** [mvdnes/spin-rs#40]
In the  `call_once()` function documentation, there is a typo at the very end of the 3rd paragraph: 

> /// When this function returns, it is guaranteed that some initialization
> /// has run and completed (it may not be the closure specified). The
> /// returned pointer points to the return value of when of those
> /// initialization closures.
> 

I think the last sentence should be something like this, but I'm not 100% sure. 

> The returned pointer points to the value returned by the initialization closure parameter, even on future invocations.

**Comment by mvdnes** [comment]
It should be something like
> The returned pointer will point to the result of the closure that was used.
Or instead of 'used', you could use 'ran'.

**Comment by kevinaboos** [comment]
Yeah, that sounds correct. Thanks for clarifying, it'd be good to update the docs too.

**Comment by mvdnes** [comment]
Resolved in 1d6cd8b.
