### ISSUE TITLE
Could not find `hint` in `core` , what 's happening?

### ISSUE THREAD

**Issue by xiaolongn100** [mvdnes/spin-rs#63]
Compiling spin v0.4.10
error[E0432]: unresolved import `core::hint`
  --> C:\Users\xiaolong\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\spin-0.4.10\src\once.rs:48:11
   |
48 | use core::hint::unreachable_unchecked as unreachable;
   |           ^^^^ Could not find `hint` in `core`

error: aborting due to previous error

If you want more information on this error, try using "rustc --explain E0432"
error: Could not compile `spin`.

To learn more, run the command again with --verbose.

**Comment by mvdnes** [comment]
I suspect you are using an old rustc version, as `core::hint` is supported starting version 1.27.

**Comment by xiaolongn100** [comment]
ok！ thanks !
