### ISSUE TITLE
Non-reserved-keyword identifier for spin::Once::try

### ISSUE THREAD

**Issue by tjhu** [mvdnes/spin-rs#71]
`try` is a reserved keyword so I have to do `r#try` if I want to use it in Rust Edition 2018([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=644d7b527c5d4f334f47fc4a7754505a)). That doesn't look very pretty. Can we rename [`spin::Once::try`](https://mvdnes.github.io/rust-docs/spin-rs/spin/struct.Once.html#method.try) into something else so that we don't have to explicitly escape the reserved keyword? 
Thanks!

**Comment by zesterer** [comment]
This has been resolved by #84 . `try` is now renamed to `get` and, additionally, has a `get_mut` equivalent.
