### ISSUE TITLE
Interest in crate maintenance.

### ISSUE THREAD

**Issue by mental32** [mvdnes/spin-rs#72]
Hello @mvdnes I'm sorry to hear that you've lost interest in maintaining this crate :disappointed: 

I've found this crate useful and took an interest in it when I used it for [a toy kernel project of mine](https://github.com/mental32/fart-joke) so I'd like to offer taking up responsibility of maintaining this crate so feel free to send me a collaborator invitation or a repository transfer request :smile:

**Comment by mvdnes** [comment]
Thank you for your interest. I have sent an invitation for becoming a collaborator.

For now I will still keep the crates.io publishing rights to myself, so please notify me when this is needed.

Good luck!
