### ISSUE TITLE
Changing Ownership

### ISSUE THREAD

**Issue by zesterer** [mvdnes/spin-rs#74]
Given that there are several feature requests open in the issues and that this project lies at the heart of many Rust projects, would you be open to transferring ownership of the repository & crate to someone else?

**Comment by mvdnes** [comment]
Yes, I would indeed be interested in transferring ownership. Unfortunately, I do not know who to choose as a new owner, and on what grounds. If you have any suggestions, feel free.

**Comment by mvdnes** [comment]
I have added you as a maintainer, so I can keep an eye on it. I will consider a transfer of ownership in the future.

**Comment by zesterer** [comment]
Thanks! Do you mind if I look into implementing a few features?

**Comment by mvdnes** [comment]
Not at all! And please let me know if you want to have a new version published.
