### ISSUE TITLE
Releasing a new version

### ISSUE THREAD

**Issue by zesterer** [mvdnes/spin-rs#79]
Several PRs were merged recently that add a significant number of features to the crate. A new version for crates.io would be welcome.

**Comment by mvdnes** [comment]
Sure. Do you want to publish 0.5.3 or 0.6.0?

**Comment by zesterer** [comment]
0.6.0. Although I don't think that any changes are actually breaking, adding support for `lock_api` and changing up the internals quite a bit calls for a new minor version in my view.

**Comment by mvdnes** [comment]
Sure, I have sent you an invite.

**Comment by zesterer** [comment]
Thanks! I'll release the new version in a little while.

**Comment by ErichDonGubler** [comment]
Does this mean that [`RUSTSEC-2019-0031`](https://rustsec.org/advisories/RUSTSEC-2019-0031.html), which states this project is unmaintained, is invalid? I've been pinged on a [PR I have that resolves that advisory](https://github.com/briansmith/ring/pull/1053#issuecomment-706247444) for `ring`, where the 0.6.0 release was noted.

**Comment by zesterer** [comment]
@ErichDonGubler Yes, it's invalid. I files a PR to update this 2 days ago. It was merged, but it seems there's a bug in `cargo-audit` that means it still shows up. Hopefully this will be fixed soon.

**Comment by zesterer** [comment]
@mvdnes If you happen to have the time, I'd much appreciate a change of the repo description to `Spin-based synchronization primitives.` since I don't seem to have permission to change it. Cheers!

**Comment by mvdnes** [comment]
:+1: Done

**Comment by djc** [comment]
> It was merged, but it seems there's a bug in cargo-audit that means it still shows up. Hopefully this will be fixed soon.

Can you link to the bug?

**Comment by zesterer** [comment]
@djc It was discussed on the rust-lang Zulip. [this PR](https://github.com/RustSec/advisory-db/pull/424) should have resolved it though.
