### ISSUE TITLE
Provide alternatives for `std::lazy::SyncLazy` type?

### ISSUE THREAD

**Issue by phil-opp** [mvdnes/spin-rs#88]
RFC https://github.com/rust-lang/rfcs/pull/2788 introduced a (still unstable) [`std::lazy`](https://doc.rust-lang.org/nightly/std/lazy/index.html) module. While the `Lazy` and `OnceCell` types of this module are also available [in `core`](https://doc.rust-lang.org/nightly/core/lazy/index.html), their `Sync` counterparts are not because of their `Mutex` dependency.

The `spin` crate already provides a [`spin::Once`](https://docs.rs/spin/0.6.0/spin/struct.Once.html) as an alternative to the [`std::lazy::SyncOnceCell`](https://doc.rust-lang.org/nightly/std/lazy/struct.SyncOnceCell.html) type (albeit with a different API). It would be useful if it would also provide an alternative to the [`std::lazy::SyncLazy`](https://doc.rust-lang.org/nightly/std/lazy/struct.SyncLazy.html) type. This way, we could avoid depending on the [`lazy_static`](https://docs.rs/lazy_static/1.4.0/lazy_static/index.html) crate.

**Comment by zesterer** [comment]
Do you think this could be implemented as a thin layer on top of `Once`, or perhaps even integrated into it? The only obstacle to that I can forsee is the `take` method but I could easily add support for something like that to `Once`.

**Comment by phil-opp** [comment]
Yeah, I think it could be a thin wrapper around `Once`. I can prepare a PR if you like.

I don't think that the `take` method is needed for that, but it might be useful on its own.

**Comment by phil-opp** [comment]
I opened a PR at https://github.com/mvdnes/spin-rs/pull/89. It's just a copy of the standard library implementation, so please let me know if you think that it needs some adjustments.

**Comment by zesterer** [comment]
Perhaps adjustments might be required in the future, but for now this good enough for inclusion. Thanks!
